version: 2

sources:
  - name: erp
    description: Sistema de dados de venda da Adventure Works
    database: fea24_9
    schema: raw_adventure_works
    tables:
      - name: creditcard
        description: Dados da tabela de cartão de crédito
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null
                  