version: 2

sources:
  - name: erp
    description: Sistema de dados de venda da Adventure Works
    database: fea24_9
    schema: raw_adventure_works
    tables:
      - name: customer
        description: Dados da fonte dos clientes.
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
      - name: person
        description: Dados da fonte de pessoas.
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

      - name: productcategory
        description: Dados da fonte de categoria de produtos.
        columns:
          - name: PRODUCTCATEGORYID
            tests:
              - unique
              - not_null

      - name: productsubcategory
        description: Dados da fonte das subcategorias dos produtos.
        columns:
          - name: productsubcategoryid
            tests:
              - unique
              - not_null

      - name: product
        description: Dados da fonte dos dados de produtos.
        columns:
          - name: productid
            tests:
              - unique
              - not_null
                  
      - name: address
        description: Dados da fonte de endereços.
        columns:
          - name: addressid
            tests:
              - unique
              - not_null

      - name: stateprovince
        description: Dados da fonte dos estados.
        columns:
          - name: STATEPROVINCEID
            tests:
              - unique
              - not_null

      - name: countryregion
        description: Dados da fonte dos países.
        columns:
          - name: COUNTRYREGIONCODE
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Dados da fonte de motivo de venda.
        columns:
          - name: SALESORDERID
            tests:
              - not_null

      - name: salesreason
        description: Dados da fonte de motivos de venda.
        columns:
          - name: SALESREASONID
            tests:
              - unique
              - not_null

