version: 2

sources:
  - name: erp
    description: Sistema de dados de venda da Adventure Works
    database: fea24_9
    schema: raw_adventure_works
    tables:
      - name: customer
        description: Dados da fonte dos clientes.
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
      - name: person
        description: Dados da fonte de pessoas.
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null

      - name: productcategory
        description: Dados da fonte de categoria de produtos.
        columns:
          - name: PRODUCTCATEGORYID
            tests:
              - unique
              - not_null

      - name: productsubcategory
        description: Dados da fonte das subcategorias dos produtos.
        columns:
          - name: productsubcategoryid
            tests:
              - unique
              - not_null
                  
                  